kind: Deployment
apiVersion: apps/v1
metadata:
  name: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: sonarqube:latest
        ports:
        - containerPort: 9000
          protocol: TCP
        volumeMounts:
        - name: sonar-data
          mountPath: "/opt/sonarqube/data/"
        - name: sonar-extensions
          mountPath: "/opt/sonarqube/extensions/"
        env:
        - name: sonar.jdbc.username
          value: sonar
        - name: sonar.jdbc.url
          value: jdbc:postgresql://postgres.default.svc.cluster.local/sonar
        - name: sonar.jdbc.password
          valueFrom:
            secretKeyRef:
              name: sonar-postgres-pword
              key: SONAR_POSTGRES_PASSWORD
      volumes:
      - name: sonar-data
        persistentVolumeClaim:
          claimName: pvc-sonarqube-data
      - name: sonar-extensions
        persistentVolumeClaim:
          claimName: pvc-sonarqube-extensions 
