apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout-noauth
  annotations:
    # remove www prefix
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ( $host ~ ^www\.(.+)$ ) {
        set $without_www $1;
        rewrite ^ $scheme://$without_www$uri 302;
      }
spec:
  rules: 
  - host: rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rex-prod
          servicePort: 80

  - host: www.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: rex-prod
          servicePort: 80

  - host: ideahopper.org
    http:
      paths:
      - path: /
        backend:
          serviceName: ideahopper-prod
          servicePort: 80

  tls:
    - secretName: tls-secret-rexsystems-co-uk
    - secretName: tls-secret-www-rexsystems-co-uk
    - secretName: tls-secret-ideahopper-org
