apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout-auth
  annotations:
    # basic auth:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: htsecret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nonprod.rexsystems.co.uk
    http:
      paths:
      - path: /dev/
        backend:
          serviceName: rex-dev
          servicePort: 80

  - host: nonprod.ideahopper.org
    http:
      paths:
      - path: /dev/
        backend:
          serviceName: ideahopper-dev
          servicePort: 80
      - path: /uat/
        backend:
          serviceName: ideahopper-uat
          servicePort: 80
 
  - host: jenkins.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080
  
  - host: sonarqube.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube
          servicePort: 9000

  tls:
  - secretName: tls-secret-nonprod-rexsystems-co-uk
  - secretName: tls-secret-nonprod-ideahopper-org
  - secretName: tls-secret-jenkins-rexsystems-co-uk
  - secretName: tls-secret-sonarqube-rexsystems-co-uk
