apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-fanout-auth
  annotations:
    # basic auth:
    nginx.ingress.kubernetes.io/auth-type: basic
    nginx.ingress.kubernetes.io/auth-secret: htsecret
    nginx.ingress.kubernetes.io/auth-realm: "Authentication Required"
    
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: nonprod.rexsystems.co.uk
    http:
      paths:
      - path: /web/dev/
        backend:
          serviceName: rexsystems-web-dev
          servicePort: 80
      - path: /api/dev/
        backend:
          serviceName: rexsystems-api-dev
          servicePort: 80

  - host: nonprod.rexapp.rexsystems.co.uk
    http:
      paths:
      - path: /web/dev/
        backend:
          serviceName: rexapp-web-dev
          servicePort: 80
      - path: /api/dev/
        backend:
          serviceName: rexapp-api-dev
          servicePort: 80

  - host: nonprod.ideahopper.org
    http:
      paths:
      - path: /web/dev/
        backend:
          serviceName: ideahopper-web-dev
          servicePort: 80
      - path: /api/dev
        backend:
          serviceName: ideahopper-api-dev
          servicePort: 80
      - path: /web/uat/
        backend:
          serviceName: ideahopper-web-uat
          servicePort: 80
      - path: /api/uat/
        backend:
          serviceName: ideahopper-api-uat
          servicePort: 80
      - path: /web/staging/
        backend:
          serviceName: ideahopper-web-staging
          servicePort: 80
      - path: /api/staging/
        backend:
          serviceName: ideahopper-api-staging
          servicePort: 80

  - host: jenkins.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: jenkins
          servicePort: 8080

  - host: sonarqube.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: sonarqube
          servicePort: 9000
  - host: artifactory.rexsystems.co.uk
    http:
      paths:
      - path: /
        backend:
          serviceName: artifactory
          servicePort: 80

  tls:
  - secretName: tls-secret-nonprod-rexsystems-co-uk
  - secretName: tls-secret-nonprod-rexapp-rexsystems-co-uk
  - secretName: tls-secret-nonprod-ideahopper-org
  - secretName: tls-secret-jenkins-rexsystems-co-uk
  - secretName: tls-secret-sonarqube-rexsystems-co-uk
  - secretName: tls-secret-artifactory-rexsystems-co-uk
